package com.icefaces.core.models;

//import org.apache.commons.lang.builder.*;

import org.apache.commons.lang3.builder.*;

import java.io.Serializable;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table R_FNC_FUNCTION
 *
 * @author OV Infrastructure Team
 * @version $Name$
 * @mbggenerated
 */
public class FunctionKey implements Comparable<FunctionKey>, Cloneable, Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MPFA.R_FNC_FUNCTION
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = -6517951083088842997L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MPFA.R_FNC_FUNCTION.FNC_APPL_ID
     *
     * @mbggenerated
     */
    private String applId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MPFA.R_FNC_FUNCTION.FNC_PARENT_FUNC_ID
     *
     * @mbggenerated
     */
    private String parentFuncId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MPFA.R_FNC_FUNCTION.FNC_FUNC_ID
     *
     * @mbggenerated
     */
    private String funcId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MPFA.R_FNC_FUNCTION.FNC_APPL_ID
     *
     * @return the value of MPFA.R_FNC_FUNCTION.FNC_APPL_ID
     * @mbggenerated
     */
    public String getApplId() {
        return applId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MPFA.R_FNC_FUNCTION.FNC_APPL_ID
     *
     * @param applId the value for MPFA.R_FNC_FUNCTION.FNC_APPL_ID
     * @mbggenerated
     */
    public void setApplId(String applId) {
        this.applId = applId == null ? null : applId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MPFA.R_FNC_FUNCTION.FNC_PARENT_FUNC_ID
     *
     * @return the value of MPFA.R_FNC_FUNCTION.FNC_PARENT_FUNC_ID
     * @mbggenerated
     */
    public String getParentFuncId() {
        return parentFuncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MPFA.R_FNC_FUNCTION.FNC_PARENT_FUNC_ID
     *
     * @param parentFuncId the value for MPFA.R_FNC_FUNCTION.FNC_PARENT_FUNC_ID
     * @mbggenerated
     */
    public void setParentFuncId(String parentFuncId) {
        this.parentFuncId = parentFuncId == null ? null : parentFuncId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MPFA.R_FNC_FUNCTION.FNC_FUNC_ID
     *
     * @return the value of MPFA.R_FNC_FUNCTION.FNC_FUNC_ID
     * @mbggenerated
     */
    public String getFuncId() {
        return funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MPFA.R_FNC_FUNCTION.FNC_FUNC_ID
     *
     * @param funcId the value for MPFA.R_FNC_FUNCTION.FNC_FUNC_ID
     * @mbggenerated
     */
    public void setFuncId(String funcId) {
        this.funcId = funcId == null ? null : funcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MPFA.R_FNC_FUNCTION
     *
     * @mbggenerated
     */
    public int compareTo(FunctionKey that) {
        return new CompareToBuilder().append(this.applId, that.applId).append(this.parentFuncId, that.parentFuncId).append(this.funcId, that.funcId).toComparison();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MPFA.R_FNC_FUNCTION
     *
     * @mbggenerated
     */
    @Override
    public Object clone() {
        try {
            return super.clone();
        } catch (CloneNotSupportedException e) {
            return null;
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MPFA.R_FNC_FUNCTION
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object o) {
        if (o == this) {
            return true;
        }
        if (o instanceof FunctionKey) {
            FunctionKey that = (FunctionKey) o;
            return new EqualsBuilder().append(this.applId, that.applId).append(this.parentFuncId, that.parentFuncId).append(this.funcId, that.funcId).isEquals();
        }
        return false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MPFA.R_FNC_FUNCTION
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        return new HashCodeBuilder().append(applId).append(parentFuncId).append(funcId).toHashCode();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MPFA.R_FNC_FUNCTION
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        return new ToStringBuilder(this, ToStringStyle.SHORT_PREFIX_STYLE).append("applId", applId).append("parentFuncId", parentFuncId).append("funcId", funcId).toString();
    }
}